param(
    [string]$FxcPath,
    [string]$SourceHeaderPath = (Join-Path $PSScriptRoot '..\include\d3d12_shader_source.h'),
    [string]$HeaderPath = (Join-Path $PSScriptRoot '..\include\d3d12_liquid_glass_bytecode.h')
)

$ErrorActionPreference = 'Stop'

if (-not $FxcPath) {
    $windowsSdkBin = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'
    $FxcPath = Get-ChildItem -LiteralPath $windowsSdkBin -Filter fxc.exe -Recurse -ErrorAction SilentlyContinue |
        Where-Object { $_.FullName -match '\\x64\\fxc\.exe$' } |
        Sort-Object FullName -Descending |
        Select-Object -First 1 -ExpandProperty FullName
}

if (-not $FxcPath -or -not (Test-Path -LiteralPath $FxcPath)) {
    throw 'fxc.exe not found. Install a Windows SDK or pass -FxcPath.'
}

$sourceHeader = [IO.File]::ReadAllText($SourceHeaderPath)

function Get-EmbeddedShaderSource {
    param([Parameter(Mandatory)][string]$Symbol)

    $pattern = 'static\s+const\s+char\s+{0}\[\]\s*=\s*R"HLSL\((?<body>[\s\S]*?)\)HLSL";' -f [Regex]::Escape($Symbol)
    $match = [Regex]::Match($sourceHeader, $pattern)
    if (-not $match.Success) {
        throw "Unable to find embedded shader source: $Symbol"
    }

    return $match.Groups['body'].Value
}

$shaderSpecs = @(
    @{ Symbol = 'kLiquidGlassVS'; Profile = 'vs_5_1' },
    @{ Symbol = 'kLiquidGlassPS'; Profile = 'ps_5_1' }
)

$temporaryDirectory = Join-Path ([IO.Path]::GetTempPath()) ("jalium-liquid-glass-bytecode-{0}-{1}" -f $PID, [Guid]::NewGuid().ToString('N'))
[void](New-Item -ItemType Directory -Path $temporaryDirectory)

try {
    $compiledShaders = @()
    $utf8WithoutBom = [Text.UTF8Encoding]::new($false)

    foreach ($shader in $shaderSpecs) {
        $hlslPath = Join-Path $temporaryDirectory ($shader.Symbol + '.hlsl')
        $csoPath = Join-Path $temporaryDirectory ($shader.Symbol + '.cso')
        [IO.File]::WriteAllText($hlslPath, (Get-EmbeddedShaderSource $shader.Symbol), $utf8WithoutBom)

        & $FxcPath /nologo /T $shader.Profile /E main /O3 /Fo $csoPath $hlslPath
        if ($LASTEXITCODE -ne 0) {
            throw "fxc failed for $($shader.Symbol) with exit code $LASTEXITCODE"
        }

        $compiledShaders += @{
            Symbol = $shader.Symbol
            Bytes = [IO.File]::ReadAllBytes($csoPath)
        }
    }

    $output = [Text.StringBuilder]::new()
    [void]$output.AppendLine('#pragma once')
    [void]$output.AppendLine('// Auto-generated pre-compiled D3D12 Liquid Glass shader bytecode.')
    [void]$output.AppendLine('// Generated by shaders/gen_liquid_glass_bytecode.ps1 (fxc /O3) - do not edit manually.')
    [void]$output.AppendLine('// The source of truth remains the embedded HLSL in d3d12_shader_source.h.')
    [void]$output.AppendLine()
    [void]$output.AppendLine('namespace liquid_glass_shader_bytecode {')

    foreach ($shader in $compiledShaders) {
        $symbol = $shader.Symbol
        $bytes = $shader.Bytes
        [void]$output.AppendLine()
        [void]$output.AppendLine("static const unsigned int ${symbol}Size = $($bytes.Length);")
        [void]$output.AppendLine("static const unsigned char ${symbol}[] = {")

        for ($index = 0; $index -lt $bytes.Length; $index++) {
            if ($index % 16 -eq 0) { [void]$output.Append('    ') }
            [void]$output.Append(('0x{0:x2}' -f $bytes[$index]))
            if ($index -lt $bytes.Length - 1) {
                if (($index + 1) % 16 -eq 0) {
                    [void]$output.Append(',')
                }
                else {
                    [void]$output.Append(', ')
                }
            }
            if (($index + 1) % 16 -eq 0) { [void]$output.AppendLine() }
        }

        if ($bytes.Length % 16 -ne 0) { [void]$output.AppendLine() }
        [void]$output.AppendLine('};')
    }

    [void]$output.AppendLine()
    [void]$output.AppendLine('} // namespace liquid_glass_shader_bytecode')
    [IO.File]::WriteAllText($HeaderPath, $output.ToString(), $utf8WithoutBom)
    Write-Host "Generated $HeaderPath"
}
finally {
    if (Test-Path -LiteralPath $temporaryDirectory) {
        Remove-Item -LiteralPath $temporaryDirectory -Recurse -Force
    }
}
